version: "3.2"
services:
  miner:
    container_name: miner
    build: "./miner"
    image: harmony-miner:casper
    restart: always
    ports:
      - "8080:8545"
    volumes:
      - type: bind
        source: ./demo
        target: /root/demo
        read_only: true
    environment:
      - GENESIS=/root/demo/casper-demo.json
      - COINBASE=cd2a3d9f938e13cd947ec05abc7fe734df8dd826
      - BLOCK_DELAY_MILLIS=5000
      - NODEKEY=41791102999c339c844880b23950704cc43aa840f3739e365323cda4dfa89e7a
    networks:
      demo:
        ipv4_address: 172.30.250.2

  validator:
    container_name: validator
    build: "./validator"
    image: harmony-validator:casper
    restart: always
    ports:
      - "8081:8545"
    volumes:
      - type: bind
        source: ./demo
        target: /root/demo
        read_only: true
    environment:
      - GENESIS=/root/demo/casper-demo.json
      - BOOTNODE=enode://3b4ca60e476367e69ddc0efd1d46652ac9799385e74aae8e90d076c7a3983d0f1e6901785097d6015032b14078164287dff714e194efb420fc70abd7d3e132b9@172.30.250.2:30303
      - VALIDATOR_KEY=c85ef7d79691fe79573b1a7064c19c1a9819ebdbd1faaab1a8ec92344438aaf4
      - VALIDATOR_DEPOSIT_ETH=2500
    networks:
      demo:
        ipv4_address: 172.30.250.3

networks:
  demo:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.30.250.0/24
